#1- clone the repository https://github.com/SoaadMohamed/CMSTask.git
#2- install docker-compose
#3- change directory to "CMSTask"
#4- create 2 directories for mysql "mysql_cnf" and "mysql_data"
#5- run command: "docker-compose -f trufla-docker-compose.yml up"
#=============================================================================
# Drupal with MySQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: MySQL
# Database name: 
# Database username: root
# Database password: 
# ADVANCED OPTIONS; Database host: mysql

version: '3.1'

services:

  mysql:
    container_name: trufla-mysql
    image: mysql:5.6.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_cnf:/etc/mysql/
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: trufla
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    ports:
    - "3306:3306"

  drupal:
    depends_on:
      - mysql
    container_name: trufla-drupal
    image: drupal:7.60-apache
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
    restart: always
